- name: Build EXE with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed --add-data "templates;templates" --add-data "static;static" --add-data "src;src" --name "Sniper_AI" app.py

      - name: Upload Finished EXE
        uses: actions/upload-artifact@v4
        with:
          name: Sniper_AI_Windows_Version
          path: dist/Sniper_AI.exe